[package]
name = "snapatac2-core"
version = "2.0.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
anndata = { git = "https://github.com/kaizhang/anndata-rs.git", rev = "730eea8495ba1884ea50308e5f03ab0cb60f9ae8" }
anyhow = "1.0"
bigtools = "0.2"
bincode = "1.3"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "d06f2b4ff189c64bc0d3f7054f4ee8d0797368ca" }
extsort = "0.4"
either = "1.8"
flate2 = "1.0"
futures = "0.3"
hora = "0.1"
kdtree = "0.7"
itertools = "0.11"
indexmap = "2.0"
indicatif = "0.17"
lexical = "6.1"
log = "0.4"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
noodles = { version = "0.53", features = ["core", "bam", "sam", "gff", "gtf"] }
nalgebra-sparse = "0.9"
polars = { version = "0.32", features = ["ndarray", "dtype-categorical"] }
rayon = "1.8"
regex = "1.6"
serde = "1.0"
statrs = "0.16"
smallvec = "1.11"
tempfile = "3.3"