name: Nightly Run

on: [push]

#on:
#  schedule:
#    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  check-for-new-commits:
    runs-on: ubuntu-latest
    outputs:
      NEW_COMMITS: ${{ steps.check-commits.outputs.NEW_COMMITS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit SHA
        id: get-latest-commit-sha
        run: echo "LATEST_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Get last run
        run: |
          workflow_id=$(basename $(github.event.workflow.url))
          repo=${{ github.repository }}
          last_run=$(gh api repos/$repo/actions/workflows/$workflow_id/runs --paginate | jq -r '.workflow_runs | map(select(.head_branch == "${{ github.event.ref }}" and .status == "completed")) | sort_by(.created_at) | .[-2]')
          last_run_date=$(echo $last_run | jq -r '.created_at')
          last_run_sha=$(echo $last_run | jq -r '.head_sha')
          echo "Last run was at: $last_run_date"
          echo "Last run SHA: $last_run_sha"
          echo "LAST_RUN_SHA=$last_run_sha" >> $GITHUB_ENV

      - name: Check if there are new commits since the last run
        id: check-commits
        run: |
          if [ "${{ env.LAST_RUN_SHA }}" == "${{ env.LATEST_COMMIT_SHA }}" ]; then
            echo "No new commits since the last run."
            echo "NEW_COMMITS=false" >> $GITHUB_ENV
          else
            echo "There are new commits since the last run."
            echo "NEW_COMMITS=true" >> $GITHUB_ENV
          fi

  conditional-job:
    runs-on: ubuntu-latest
    needs: check-for-new-commits
    steps:
      - name: Conditional Job
        env:
          NEW_COMMITS: ${{ needs.check-for-new-commits.outputs.NEW_COMMITS }}
        if : ${{ env.NEW_COMMITS == 'true' }}
        run: |
          echo "This job runs only if there are new commits since the last run."
          # Add your commands for the conditional job here.